/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InventoryCategory = { 'Seals' : null } |
  { 'Caps' : null } |
  { 'FilledGallons' : null } |
  { 'EmptyContainers' : null };
export interface InventoryItem {
  'id' : bigint,
  'lastUpdated' : bigint,
  'quantity' : bigint,
  'category' : InventoryCategory,
}
export interface _SERVICE {
  'createInventoryItem' : ActorMethod<[boolean], undefined>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getInventoryItem' : ActorMethod<[bigint], InventoryItem>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];