/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InventoryCategory = IDL.Variant({
  'Seals' : IDL.Null,
  'Caps' : IDL.Null,
  'FilledGallons' : IDL.Null,
  'EmptyContainers' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'quantity' : IDL.Int,
  'category' : InventoryCategory,
});

export const idlService = IDL.Service({
  'createInventoryItem' : IDL.Func([IDL.Bool], [], []),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InventoryCategory = IDL.Variant({
    'Seals' : IDL.Null,
    'Caps' : IDL.Null,
    'FilledGallons' : IDL.Null,
    'EmptyContainers' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'quantity' : IDL.Int,
    'category' : InventoryCategory,
  });
  
  return IDL.Service({
    'createInventoryItem' : IDL.Func([IDL.Bool], [], []),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getInventoryItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };